train:
  id: csgo
  size: [320, 240]
num_actions: 39
path_data_low_res: C:\Users\ifrat\Documents\Python Scripts\AI-MarioKart64\diamond\processed\low_res
path_data_full_res: C:\Users\ifrat\Documents\Python Scripts\AI-MarioKart64\diamond\processed\full_res
keymap: csgo
